### ISSUE TITLE
Server se sesuje če spammaš slika napre/nazaj

### ISSUE THREAD

**Issue by marmiha** [matejbizjak/TrapIT#32]

**Comment by marmiha** [comment]
Onemogočanje, obeh gumbov bi mogoče rešilo problem?

**Comment by matejbizjak** [comment]
Bom pogledal. Verjetno bo tako najlažje rešiti, ja.

**Comment by matejbizjak** [comment]
Popravljeno: 
![image](https://user-images.githubusercontent.com/17526489/43721110-34af2054-9992-11e8-8729-1d59e8038f77.png)
